### ISSUE TITLE
AreaManagement driver: Area counts are not exposed when a Level has 0 devices

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#243]
Currently, when a level has 0 devices detected, the exposed `zone-___:areas.values` status becomes `[]`, which is problematic because the frontend cannot set the area colour to green (because AreaManagaement is not exposing the area ids).
e.g.
```
"zone-FBkxA1Php8u:areas": {
        "value": [],
```

The driver behaviour should change such that even when the level has 0 devices, the `zone-___:areas` status should still have a `values` array that contains the area ids, with `count: 0`, like this:
```
"zone-FBkxA1Php8u:areas": {
        "value": [
            {
                "area_id": "area-HOTDESK.06-status",
                "name": "L6 Hot Desks",
                "count": 0
            }
        ],
```

I tried to resolve this on my own but have been unable to determine the cause of the behaviour. The `update_level_locations` function's logic reads like it would unconditionally add all the area details to `zone-___:areas.values`, so I'm not sure why it doesn't appear when the Level's device count is 0.

**Comment by stakach** [comment]
possibly resolved in PlaceOS/drivers@a16d031

**Comment by w-le** [comment]
yes confirmed fixed - thanks!
so was a divide by 0 error being ignored
funny i though it might have to do with that rescue and was looking out for that log error output on line 482. I didn't see log output so therefore assumed it was not erroring/catching - should've have double checked the `log_location_parsing` func! it must've have not been working

**Comment by w-le** [comment]
Damn so looks like this issue is actually still present even in the latest version of AreaMgmt. 
Currently there are a few floors with 0 devices present (after "iPhones only" filter is applied), and just like before we are seeing:
```
"zone-FBkxA1Php8u:areas": {
        "value": [],
```

Any thoughts on what else could be causing the issue? Perhaps one of the neighboring drivers that push the data to areamgmt?
