### ISSUE TITLE
dna spaces: Error "missing JSON attribute: tags"

### ISSUE THREAD

**Issue by w-le** [PlaceOS/drivers#369]
https://github.com/PlaceOS/drivers/blob/5e09eb491fb99f71135ccbaffad76a1f7de58b20/drivers/cisco/dna_spaces/device.cr#L12

Should we just change that line to `getter tags : Array(String)?` ?

```
Missing JSON attribute: tags
  parsing Cisco::DNASpaces::Device at line 1, column 261
  parsing Cisco::DNASpaces::DeviceLocationUpdate#device at line 1, column 252
  parsing Cisco::DNASpaces::DeviceLocationUpdateWrapper#deviceLocationUpdate at line 1, column 228 (JSON::SerializableError)
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:9:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:80:1 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:12:3 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:269:19 in 'process_events'
```

**Comment by stakach** [comment]
fixed in 8a88c7f0b0fbf6b55784ea9cc8dc66a9ea1c7888

**Comment by w-le** [comment]
I pulled the drivers repo (now on 1af550a2f940667cd1cbe613dc6f2c6e99ad4e8e) and recompiled the DNA driver, however the same error still occurs

<img width="671" alt="Screen Shot 2022-10-05 at 8 58 21 pm" src="https://user-images.githubusercontent.com/10395560/194065943-b3b71f4f-cd3c-4168-bd6f-92c89ec7d6de.png">

```
Missing JSON attribute: tags
  parsing Cisco::DNASpaces::UserPresence::User at line 1, column 301
  parsing Cisco::DNASpaces::UserPresence#user at line 1, column 294
  parsing Cisco::DNASpaces::UserPresenceWrapper#userPresence at line 1, column 219 (JSON::SerializableError)
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:9:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:101:1 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:12:3 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:269:19 in 'process_events'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:374:34 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
Caused by: Missing JSON attribute: tags
  parsing Cisco::DNASpaces::UserPresence::User at line 1, column 301
  parsing Cisco::DNASpaces::UserPresence#user at line 1, column 294 (JSON::SerializableError)
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:4:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:4:3 in 'new'
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:9:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:101:1 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:12:3 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:269:19 in 'process_events'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:374:34 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
Caused by: Missing JSON attribute: tags
  parsing Cisco::DNASpaces::UserPresence::User at line 1, column 301 (JSON::SerializableError)
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:7:5 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:7:5 in 'new'
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:4:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/user_presence.cr:4:3 in 'new'
  from /usr/share/crystal/src/json/serialization.cr:159:7 in 'initialize:__pull_for_json_serializable'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:9:3 in 'new_from_json_pull_parser'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:101:1 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces/events.cr:12:3 in 'new'
  from /usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:269:19 in 'process_events'
  from repositories/drivers/drivers/cisco/dna_spaces.cr:374:34 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
